"use server";

import { revalidatePath } from "next/cache";
import { getUserClaims } from "@/lib/auth/get-user-claims";
import { createServiceRoleClient } from "@/lib/supabase/server";
import { hasRole } from "@/lib/auth/role-redirect";
import { monthlyTotal } from "@/lib/modules";

/* The platform's own books.

   Everything else on this dashboard reported what was agreed. These actions
   record what arrived, which is a different number and the only one that pays
   the bills. */

async function requirePlatform() {
  const claims = await getUserClaims();
  if (!claims || !hasRole(claims, "platform_admin")) throw new Error("غير مصرح");
  return claims;
}

const money = (v: number) => Math.round((Number(v) || 0) * 1000) / 1000;

/** Issue this clinic's invoice for a period, priced from its contract.

    Deliberately not automatic. Invoicing a clinic mid-dispute, or one whose
    terms are being renegotiated this week, is the operator's call — and an
    invoice generated by a cron at 3am is one nobody remembers agreeing to. */
export async function issueInvoice(input: {
  clinicId: string;
  periodStart: string;
  periodEnd: string;
  includeSetupFee?: boolean;
  notes?: string;
}) {
  const claims = await requirePlatform();
  const sb = await createServiceRoleClient();

  if (!/^\d{4}-\d{2}-\d{2}$/.test(input.periodStart) || !/^\d{4}-\d{2}-\d{2}$/.test(input.periodEnd)) {
    return { ok: false as const, reason: "تاريخ غير صالح" };
  }
  if (input.periodEnd <= input.periodStart) {
    return { ok: false as const, reason: "نهاية الفترة قبل بدايتها" };
  }

  const { data: ent } = await sb.from("clinic_entitlements")
    .select("base_price_omr, per_doctor_omr, setup_fee_omr, contracted_doctors, discount_pct")
    .eq("clinic_id", input.clinicId).maybeSingle();
  if (!ent) {
    return { ok: false as const, reason: "لا يوجد اتفاق لهذه العيادة — احفظ الاتفاق أولاً" };
  }

  const base = Number(ent.base_price_omr ?? 0);
  const perDoc = Number(ent.per_doctor_omr ?? 0);
  const docs = Number(ent.contracted_doctors ?? 0);
  const discountPct = Number(ent.discount_pct ?? 0);

  const subtotal = money(base + perDoc * docs);
  const net = monthlyTotal({
    basePriceOmr: base, perDoctorOmr: perDoc,
    contractedDoctors: docs, discountPct,
  });
  const discount = money(subtotal - net);

  /* The setup fee is once, at the start of the relationship. Offering it on
     every invoice would let a slip bill it twice, so it is only offered when no
     earlier invoice has already carried it. */
  let setup = 0;
  if (input.includeSetupFee) {
    const { data: prior } = await sb.from("platform_invoices")
      .select("id").eq("clinic_id", input.clinicId).gt("setup_fee_omr", 0)
      .neq("status", "void").limit(1);
    if (prior?.length) {
      return { ok: false as const, reason: "رسوم التأسيس مفوترة سابقاً لهذه العيادة" };
    }
    setup = money(Number(ent.setup_fee_omr ?? 0));
  }

  /* From a sequence, not from count()+1 — two invoices issued in the same
     second would otherwise collide on the one field that must be unique. */
  const { data: number, error: numErr } = await sb.rpc("next_platform_invoice_number");
  if (numErr || !number) return { ok: false as const, reason: "تعذّر توليد رقم الفاتورة" };

  const due = new Date(Date.now() + 14 * 86_400_000).toISOString().slice(0, 10);

  const { data: inv, error } = await sb.from("platform_invoices").insert({
    clinic_id: input.clinicId,
    number,
    period_start: input.periodStart,
    period_end: input.periodEnd,
    subtotal_omr: subtotal,
    setup_fee_omr: setup,
    discount_omr: discount,
    total_omr: money(net + setup),
    due_at: due,
    notes: input.notes?.trim() || null,
    created_by: claims.sub,
  }).select("id, number, total_omr").single();

  if (error) {
    if (/duplicate|unique/i.test(error.message)) {
      return { ok: false as const, reason: "فاتورة هذه الفترة صادرة بالفعل" };
    }
    return { ok: false as const, reason: `تعذّر إصدار الفاتورة: ${error.message}` };
  }

  revalidatePath("/platform-admin/billing");
  revalidatePath(`/platform-admin/clinics/${input.clinicId}`);
  return { ok: true as const, id: inv.id as string, number: inv.number as string, total: Number(inv.total_omr) };
}

/** Money arrived. The invoice's status follows from this, set by a trigger. */
export async function recordPlatformPayment(input: {
  invoiceId: string;
  amountOmr: number;
  method: "bank_transfer" | "cash" | "thawani" | "card" | "other";
  paidAt?: string;
  reference?: string;
}) {
  const claims = await requirePlatform();
  const sb = await createServiceRoleClient();

  const amount = money(input.amountOmr);
  if (amount <= 0) return { ok: false as const, reason: "المبلغ يجب أن يكون أكبر من صفر" };

  const { data: inv } = await sb.from("platform_invoices")
    .select("id, clinic_id, total_omr, status").eq("id", input.invoiceId).maybeSingle();
  if (!inv) return { ok: false as const, reason: "الفاتورة غير موجودة" };
  if (inv.status === "void") return { ok: false as const, reason: "الفاتورة ملغاة" };

  const { data: prior } = await sb.from("platform_payments")
    .select("amount_omr").eq("invoice_id", input.invoiceId);
  const already = (prior ?? []).reduce((s, p) => s + Number(p.amount_omr ?? 0), 0);
  const outstanding = money(Number(inv.total_omr) - already);
  if (amount > outstanding + 0.0005) {
    return { ok: false as const, reason: `المتبقي على الفاتورة ${outstanding.toFixed(3)} ر.ع فقط` };
  }

  const { error } = await sb.from("platform_payments").insert({
    invoice_id: input.invoiceId,
    clinic_id: inv.clinic_id,
    amount_omr: amount,
    method: input.method,
    paid_at: input.paidAt ? new Date(input.paidAt).toISOString() : new Date().toISOString(),
    reference: input.reference?.trim() || null,
    recorded_by: claims.sub,
  });
  if (error) return { ok: false as const, reason: `تعذّر تسجيل الدفعة: ${error.message}` };

  revalidatePath("/platform-admin/billing");
  revalidatePath("/platform-admin/economy");
  revalidatePath(`/platform-admin/clinics/${inv.clinic_id}`);
  return { ok: true as const, settled: amount >= outstanding - 0.0005 };
}

/** Cancel an invoice that should not have been issued.

    Never deleted. An invoice number that vanishes is the one thing an
    accountant will not accept, so it stays in the sequence marked void. */
export async function voidInvoice(invoiceId: string, reason: string) {
  await requirePlatform();
  const sb = await createServiceRoleClient();

  const why = reason.trim();
  if (!why) return { ok: false as const, reason: "اكتب سبب الإلغاء — يبقى في السجل" };

  const { data: paid } = await sb.from("platform_payments")
    .select("id").eq("invoice_id", invoiceId).limit(1);
  if (paid?.length) {
    return { ok: false as const, reason: "الفاتورة عليها دفعات مسجّلة — احذف الدفعة أولاً إن كانت خطأ" };
  }

  const { error } = await sb.from("platform_invoices")
    .update({ status: "void", notes: `ملغاة: ${why}` }).eq("id", invoiceId);
  if (error) return { ok: false as const, reason: "تعذّر إلغاء الفاتورة" };

  revalidatePath("/platform-admin/billing");
  return { ok: true as const };
}

/** Remove a payment recorded by mistake. The invoice reopens by trigger. */
export async function deletePlatformPayment(paymentId: string) {
  await requirePlatform();
  const sb = await createServiceRoleClient();
  const { error } = await sb.from("platform_payments").delete().eq("id", paymentId);
  if (error) return { ok: false as const, reason: "تعذّر حذف الدفعة" };
  revalidatePath("/platform-admin/billing");
  revalidatePath("/platform-admin/economy");
  return { ok: true as const };
}

/** Issue this month's invoice for every active clinic that has no invoice yet.

    One button rather than a schedule: the operator sees exactly who is about to
    be billed and how much before anything is written. */
export async function issueMonthlyRun(monthISO: string) {
  await requirePlatform();
  const sb = await createServiceRoleClient();

  if (!/^\d{4}-\d{2}$/.test(monthISO)) return { ok: false as const, reason: "شهر غير صالح" };
  const start = `${monthISO}-01`;
  const [y, m] = monthISO.split("-").map(Number);
  const end = new Date(Date.UTC(y, m, 1)).toISOString().slice(0, 10);

  const { data: clinics } = await sb.from("tawd_clinics")
    .select("id, name, name_ar").eq("status", "active");

  const issued: { clinic: string; number: string; total: number }[] = [];
  const skipped: { clinic: string; why: string }[] = [];

  for (const c of clinics ?? []) {
    const label = (c.name_ar ?? c.name) as string;
    const r = await issueInvoice({
      clinicId: c.id as string, periodStart: start, periodEnd: end,
    });
    if (r.ok) issued.push({ clinic: label, number: r.number, total: r.total });
    else skipped.push({ clinic: label, why: r.reason });
  }

  revalidatePath("/platform-admin/billing");
  return { ok: true as const, issued, skipped };
}
